---
- hosts: all
  vars_files:
    - env_vars/base.yml
  gather_facts: false
  become: yes

  tasks:
    - name: Install system packages
      apt: pkg={{ item }} update-cache=yes
      with_items: "{{ system_packages }}"

    - name: Create directory for app
      file: path={{ install_root }}/{{ project_name }} state=directory owner=www-data

    - name: Create directory for ssh
      file: path=/var/www/.ssh state=directory owner=www-data

    - name: Create directory for media
      file: path={{ install_root }}/media state=directory owner=www-data

    - name: Save ssh key to server
      copy: src={{ ssh_private_key }} dest=/var/www/.ssh/id_rsa mode=600 owner=www-data

    - name: make sure postgresql server is running
      service: name=postgresql state=started

    - name: create database
      become_user: postgres
      postgresql_db: name={{ db_name }}

    - name: create database user
      become_user: postgres
      postgresql_user: db={{ db_name }} name={{ db_user }} password={{ db_password }} priv=ALL

    - name: remove default nginx site
      file: path=/etc/nginx/sites-enabled/default state=absent

- include: deploy.yml
