postgresql_version: 9.4
postgresql_backup_local_dir: ~postgres/backup
postgresql_backup_active_dir: "{{ postgresql_backup_local_dir }}/active"
postgresql_backup_mail_recipient: postgres
postgresql_backup_rotate: true
postgresql_pgdata: /var/lib/pgsql/{{ postgresql_version }}/data
postgresql_conf_dir: /var/lib/pgsql/{{ postgresql_version }}/data
postgresql_service_name: postgresql-{{ postgresql_version }}
