- name: Install PostgreSQL
  dnf: name={{ item }} state=installed
  with_items:
    - postgresql
    - postgresql-server
    - postgresql-contrib


- name: Ensure database is created
  sudo_user: postgres
  postgresql_db: name={{ db_name }}
                 encoding='UTF-8'
                 lc_collate='es_ES.UTF-8'
                 lc_ctype='es_ES.UTF-8'
                 template='template0'
                 state=present

- name: Ensure the PostgreSQL service is running
  service: name=postgresql state=started enabled=yes

- name: Ensure user has access to the database
  postgresql_user: db={{ db_name }}
                   name={{ db_user }}
                   password={{ db_password }}
                   priv=ALL
                   state=present

- name: Ensure user does not have unnecessary privileges
  become_user: postgres
  postgresql_user: name={{ db_user }}
                   role_attr_flags=NOSUPERUSER,NOCREATEDB
                   state=present
